FROM node:18.5.0 as builder

# Build frontend code which added upload/download button
WORKDIR /app
COPY html/package.json /app/
COPY html/yarn.lock /app/
RUN yarn install
COPY html/ /app/
RUN yarn run build

FROM ghcr.io/dtzar/helm-kubectl:3.9
SHELL [ "/bin/bash", "-c" ]

RUN echo "https://dl-cdn.alpinelinux.org/alpine/edge/testing/" >> /etc/apk/repositories \
    && apk -U upgrade \
    && apk add --no-cache ca-certificates lrzsz \
    && ln -s /usr/bin/lrz	/usr/bin/rz \
    && ln -s /usr/bin/lsz	/usr/bin/sz \
    && apk add bash-completion \
    && source /usr/share/bash-completion/bash_completion \
    && echo 'source <(kubectl completion bash)' >>~/.bashrc \
    && echo 'alias k=kubectl' >>~/.bashrc \
    && echo 'complete -o default -F __start_kubectl k' >>~/.bashrc

RUN ttydArch="$(arch)" && echo "Building arch of $ttydArch.." \
    && curl -LO https://github.com/tsl0922/ttyd/releases/download/1.6.3/ttyd.${ttydArch} \
    && chmod +x ttyd.${ttydArch} \
    && mv ttyd.${ttydArch} /usr/local/bin/ttyd \
    && which ttyd \
    && mkdir kubeconf \
    && tools_arch="$(arch | sed s/aarch64/arm64/ | sed s/x86_64/amd64/)" && echo "Building tools_arch of $tools_arch.." \
    && curl -fsSLO https://github.com/karmada-io/karmada/releases/download/v1.2.0/kubectl-karmada-linux-${tools_arch}.tgz \
    && tar -zxf kubectl-karmada-linux-${tools_arch}.tgz \
    && chmod +x kubectl-karmada \
    && mv kubectl-karmada /usr/local/bin/kubectl-karmada \
    && which kubectl-karmada \
    && rm -rf kubectl-karmada-linux-* \
    && curl -fsSLO https://github.com/etcd-io/etcd/releases/download/v3.4.20/etcd-v3.4.20-linux-${tools_arch}.tar.gz \
    && tar -zxf etcd-v3.4.20-linux-${tools_arch}.tar.gz \
    && chmod +x etcd-v3.4.20-linux-${tools_arch}/etcdctl \
    && mv etcd-v3.4.20-linux-${tools_arch}/etcdctl /usr/local/bin/etcdctl \
    && which kubectl-karmada \
    && rm -rf etcd-v3.4.20-linux-*

COPY --from=builder /app/dist/inline.html index.html
ENTRYPOINT ttyd
