{{- if .Values.sshproxy.enabled}}
{{- $privateKey := genPrivateKey "ecdsa" -}}
{{- $secretName := printf "%s-private-key" (include "cloudtty.sshproxy.fullname" .) -}}
{{- $secretInstance := (lookup "v1" "Secret" .Release.Namespace $secretName) -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/ssh-auth
data:
  # helm 的 lookup 函数
  # https://helm.sh/zh/docs/chart_template_guide/functions_and_pipelines/#%E4%BD%BF%E7%94%A8lookup%E5%87%BD%E6%95%B0
{{- if and $secretInstance (get $secretInstance.data "ssh-privatekey") }}
  ssh-privatekey: {{ get $secretInstance.data "ssh-private-key" }}
{{- else }}
  ssh-privatekey: {{ printf "%s" $privateKey | b64enc }}
{{- end }}

{{- end }}
