apiVersion: apps/v1
kind: Deployment
metadata:
  name: sshproxy
  namespace: cloudtty-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sshproxy
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        image-selectors: '[]'
      labels:
        app: sshproxy
    spec:
      containers:
        - image: release-ci.daocloud.io/cloudtty/cloudproxy:v0.1
          imagePullPolicy: IfNotPresent
          name: container-1
          ports:
            - containerPort: 2222
              protocol: TCP
          command:
            - /bin/sshpiperd
            - /bin/sshproxy
          securityContext:
            privileged: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /ssh-server-key
              name: sshpiper-server-key
              readOnly: true
          env:
            - name: SSHPIPERD_SERVER_KEY
              value: /ssh-server-key/ssh_host_ed25519_key
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        - name: sshpiper-server-key
          secret:
            secretName: sshpiper-server-key
            items:
              - key: server_key
                path: ssh_host_ed25519_key
            defaultMode: 420

