kind: Secret
apiVersion: v1
metadata:
  name: sshpiper-server-key
  namespace: cloudtty-system
data:
  server_key: >-
    LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUF0egpjMmd0WldReU5UVXhPUUFBQUNDc0paaVB5c2l4ZEgyOGtQdS94NHB0Y2J6RmhHTEd6ZXJHRXozRnQ3TTNzUUFBCkFJaE8wVFZ3VHRFMWNBQUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDQ3NKWmlQeXNpeGRIMjhrUHUveDRwdGNiekYKaEdMR3plckdFejNGdDdNM3NRQUFBRUFxR0JhbDYwWll6dkNNMTZLajRNR0hzSWIyYnovZWZ2ek45dUI5Y3FEVwpUS3dsbUkvS3lMRjBmYnlRKzcvSGltMXh2TVdFWXNiTjZzWVRQY1czc3pleEFBQUFBQUVDQXdRRgotLS0tLUVORCBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0=
type: Opaque
